import { createApi } from "@reduxjs/toolkit/query/react";
import axiosBaseQuery from "./axiosBaseQuery";

export const baseApi = createApi({
  reducerPath: "baseApi",
  baseQuery: axiosBaseQuery(),
  tagTypes: [
    "USERS",
    "USER",
    "CUSTOMERS",
    "CUSTOMER",
    "PRODUCT_VERIFICATION",
    "ME",
    "REVIEWS",
    "PRODUCT_BLOG",
    "REVIEW",
    "BRAND",
    "BRANDS",
    "POSSTATS",
    "CATEGORIES",
    "RETURNS",
    "COURIER_SETTINGS",
    "COURIER_SETTING",
    "RETURN",
    "CATEGORY",
    "LEADS",
    "LEAD",
    "PRODUCTS",
    "PRODUCT",
    "ORDERS",
    "ORDER",
    "COURIERS",
    "COURIER",
    "PRODUCT_PURCHASES",
    "PRODUCT_PURCHASE",
    "MY_ORDERS",
    "DASHBOARD_OVERVIEW",
    "DASHBOARD_STATS",
    "COUPONS",
  ],
  endpoints: () => ({}),
});
